version: '3.8'

services:
  mysql:
    image: mysql:8.0.36
    container_name: gearshow-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gearshow
      MYSQL_USER: gearshow
      MYSQL_PASSWORD: gearshow
    volumes:
      - gearshow-mysql-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password --skip-log-bin

  localstack:
    image: localstack/localstack:3.0
    container_name: gearshow-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=ap-northeast-2
    volumes:
      - gearshow-localstack-data:/var/lib/localstack

volumes:
  gearshow-mysql-data:
  gearshow-localstack-data:
